# Generated by Django 4.1.7 on 2024-03-20 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Имя исполнителя')),
                ('slug', models.SlugField(max_length=250, verbose_name='Slug')),
                ('context', models.TextField(blank=True, verbose_name='Описание')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='Возраст')),
            ],
            options={
                'verbose_name': 'Исполнитель',
                'verbose_name_plural': 'Исполнители',
                'ordering': ['-time_create'],
            },
        ),
        migrations.AddIndex(
            model_name='musician',
            index=models.Index(fields=['-time_create'], name='music_music_time_cr_d9b408_idx'),
        ),
    ]
