# Generated by Django 4.1.7 on 2024-03-21 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_alter_musician_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=models.SlugField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='musician',
            name='tagged',
            field=models.ManyToManyField(default=None, null=True, related_name='tagged', to='music.tagged'),
        ),
    ]
