# Generated by Django 4.1.7 on 2024-03-27 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_alter_genre_slug_alter_musician_tagged'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads_files')),
            ],
        ),
        migrations.AlterField(
            model_name='musician',
            name='tagged',
            field=models.ManyToManyField(default=None, related_name='tagged', to='music.tagged'),
        ),
    ]
