# Generated by Django 4.1.7 on 2024-03-27 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_uploadfiles_alter_musician_tagged'),
    ]

    operations = [
        migrations.AddField(
            model_name='musician',
            name='photo',
            field=models.ImageField(default=None, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
    ]
