# Generated by Django 4.1.7 on 2024-03-27 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_musician_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='genre',
            field=models.ForeignKey(db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='genre', to='music.genre'),
        ),
        migrations.AlterField(
            model_name='musician',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='musician',
            name='tagged',
            field=models.ManyToManyField(blank=True, default=None, related_name='tagged', to='music.tagged'),
        ),
    ]
