# Generated by Django 4.1.7 on 2024-03-27 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_alter_musician_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='genre', to='music.genre'),
        ),
    ]
